spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:db;mode=MySQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: test
    password: test
    jpa:
      hibernate:
        hbm2ddl:
          auto: create
        show_sql: true
        format_sql: true
