spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/belt_cutting_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pass
    jpa:
      open-in-view: false
  flyway:
    locations: classpath:db/migration/dev/