spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: test
    password: test
    jpa:
      open-in-view: false
  flyway:
    locations: classpath:db/migration/test/