server:
  error:
    include-message: always
    include-binding-errors: always

belt-cutting:
  security:
    jwt:
      secret: eitu9aichae7eitee9XiciweishohW3pieshaifasosai5xie9Oomobulohyu8ie
      access-expire-in: 10m
      refresh-expire-in: 3d
    admins:
      admin:
        email: sammail@sammail.com
        password: fua9eeF1ahphooy5eth9ooth1iebee0AeWahyob4lai4cha3goohaewoh0gicieJ

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/belt_cutting_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: pass
    jpa:
      open-in-view: false

springdoc:
  show-actuator: true

management:
  endpoint:
    health:
      show-details: when_authorized
