spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:h2:mem:db;MODE=PostgreSQl;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: test
    password: test
    jpa:
      hibernate:
        ddl-auto: update